version: '3'
services:
  web:
    build: .
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
    volumes:
      - './app:/app'
    ports:
      - "5000:5000"

  db:
    image: postgis/postgis
    environment:
      POSTGRES_PASSWORD: qgis
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
