version: '3'
services:
  web:
    image: ghcr.io/raymond-devries/osm-postgis-manager-web:latest
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
      PGPASSWORD: qgis
      LOCAL_POSTGRES_PORT: 5433
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - osm_files:/app/osm_files

  db:
    image: postgis/postgis
    environment:
      POSTGRES_PASSWORD: qgis
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  osm_files:
